"""v2+v3: multi-user (invite codes, is_active) + quiet hours + daily digest

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-29

v3 — multi-user:
  - users.is_active: only True users can interact with the bot (admins from
    TELEGRAM_ADMIN_IDS are auto-promoted on /start). Existing rows are
    backfilled to True so v1-era users keep working.
  - users.invited_by / users.joined_at: provenance for who invited whom.
  - invite_codes: short single-use redemption codes generated by /invite.

v2 — quiet hours + digest:
  - users.quiet_from / users.quiet_to: local-time HH:MM TIME columns. NULL =
    no quiet hours. When set, scheduler defers pings landing inside the
    window to the next active edge.
  - users.digest_local_time: HH:MM TIME. NULL = no daily digest. Bot pushes
    `render_summary_text` once per local day at this time.
  - users.last_digest_at: dedup timestamp so the digest tick fires at most
    once per day per user even if the loop runs more often.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # --- v3: multi-user columns on users ---
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "invited_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Existing users (single-tenant era) keep working — flip them active.
    op.execute("UPDATE users SET is_active = true WHERE is_active = false")
    op.execute(
        "UPDATE users SET joined_at = COALESCE(joined_at, created_at) WHERE joined_at IS NULL"
    )

    # --- v2: quiet hours + digest ---
    op.add_column("users", sa.Column("quiet_from", sa.Time(), nullable=True))
    op.add_column("users", sa.Column("quiet_to", sa.Time(), nullable=True))
    op.add_column("users", sa.Column("digest_local_time", sa.Time(), nullable=True))
    op.add_column(
        "users",
        sa.Column("last_digest_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- v3: invite_codes ---
    op.create_table(
        "invite_codes",
        sa.Column("code", sa.String(16), primary_key=True),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "used_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_invite_codes_unused",
        "invite_codes",
        ["created_at"],
        postgresql_where=sa.text("used_by IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_invite_codes_unused", table_name="invite_codes")
    op.drop_table("invite_codes")
    op.drop_column("users", "last_digest_at")
    op.drop_column("users", "digest_local_time")
    op.drop_column("users", "quiet_to")
    op.drop_column("users", "quiet_from")
    op.drop_column("users", "joined_at")
    op.drop_column("users", "invited_by")
    op.drop_column("users", "is_active")
